### ISSUE TITLE
Note-Info Form not auto-populating on click on Edit 

### ISSUE THREAD

**Issue by JavaKaran** [Piyush55dude/notezipper#5]
After clickcing on edit button the note information is not auto populating with the information. I have checked with everything but it is working the same in every case 

  ```
useEffect(() => {
    const fetching = async () => {
      const { data } = await axios.get(`/api/notes/${match.params.id}`);

      setTitle(data.title);
      setContent(data.content);
      setCategory(data.category);
      setDate(data.updatedAt);
    };

    fetching();
  }, [match.params.id, date]);
```

**Comment by piyush-eon** [comment]
Make sure your inputs are controlled, not uncontrolled.

**Comment by CourageOI** [comment]
I am still having the same issue. The get request from the useEffect isn't loading the note from the database
