### ISSUE TITLE
Mongo DB Connection Error

### ISSUE THREAD

**Issue by route-2** [Piyush55dude/notezipper#7]
useNewUrlParser, useUnifiedTopology, useFindAndModify, and useCreateIndex are no longer supported options. Mongoose 6 always behaves as if useNewUrlParser, useUnifiedTopology, and useCreateIndex are true, and useFindAndModify is false. Please remove these options from your code.
in db.js of the config file in backend.
Solution to the UseCreateIndex error

**Comment by piyush-eon** [comment]
Please use the version that I have used in the project
