### ISSUE TITLE
This is not issue. Doubt!!

### ISSUE THREAD

**Issue by Badrinathan-S** [Piyush55dude/notezipper#8]
https://github.com/piyush-eon/notezipper/blob/02c46832a574d652c3f4a5166a291d704085e504/frontend/src/screens/SingleNote/SingleNote.js#L34

how it is getting the data form backend with out bearer token!. please explain.

Thanks for your help!

**Comment by piyush-eon** [comment]
@Badrinathan-S Because this is a public API, only protected APIs require bearer token.

**Comment by Badrinathan-S** [comment]
Hey completed!

http://memo-desk.herokuapp.com/home

Thanks for the amazing videos!!!

**Comment by Badrinathan-S** [comment]
Hello piyus need alternative for heroku app. Already hosted sites are dead. Help Help!!
